feat: intra: 프론트 빌드 도커 들어가기 전에

diff --git a/next/Dockerfile b/next/Dockerfile
--- a/next/Dockerfile
+++ b/next/Dockerfile
@@ -1,33 +1,33 @@
 FROM node:18-alpine AS base
 
 # Install dependencies only when needed
-FROM base AS deps
-# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
-RUN apk add --no-cache libc6-compat
-WORKDIR /app
+# FROM base AS deps
+# # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+# RUN apk add --no-cache libc6-compat
+# WORKDIR /app
 
-# Install dependencies based on the preferred package manager
-COPY ./package.json package-lock.json ./
-# RUN \
-#   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-#   elif [ -f package-lock.json ]; then npm ci; \
-#   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
-#   else echo "Lockfile not found." && exit 1; \
-#   fi
-RUN npm ci
+# # Install dependencies based on the preferred package manager
+# COPY ./package.json package-lock.json ./
+# # RUN \
+# #   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+# #   elif [ -f package-lock.json ]; then npm ci; \
+# #   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+# #   else echo "Lockfile not found." && exit 1; \
+# #   fi
+# RUN npm ci
 
-# Rebuild the source code only when needed
-FROM base AS builder
-WORKDIR /app
-COPY --from=deps /app/node_modules ./node_modules
-COPY . .
+# # Rebuild the source code only when needed
+# FROM base AS builder
+# WORKDIR /app
+# COPY --from=deps /app/node_modules ./node_modules
+# COPY . .
 
-# Next.js collects completely anonymous telemetry data about general usage.
-# Learn more here: https://nextjs.org/telemetry
-# Uncomment the following line in case you want to disable telemetry during the build.
-# ENV NEXT_TELEMETRY_DISABLED=1
+# # Next.js collects completely anonymous telemetry data about general usage.
+# # Learn more here: https://nextjs.org/telemetry
+# # Uncomment the following line in case you want to disable telemetry during the build.
+# # ENV NEXT_TELEMETRY_DISABLED=1
 
-RUN npm run build; 
+# RUN npm run build; 
 
 # Production image, copy all the files and run next
 FROM base AS runner
@@ -40,7 +40,8 @@ ENV NODE_ENV=production
 RUN addgroup --system --gid 1001 nodejs
 RUN adduser --system --uid 1001 nextjs
 
-COPY --from=builder /app/public ./public
+COPY ./public ./public
+# COPY ./.next ./.next
 
 # Set the correct permission for prerender cache
 RUN mkdir .next
@@ -48,8 +49,8 @@ RUN chown nextjs:nodejs .next
 
 # Automatically leverage output traces to reduce image size
 # https://nextjs.org/docs/advanced-features/output-file-tracing
-COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
-COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+COPY --chown=nextjs:nodejs ./.next/standalone ./
+COPY  --chown=nextjs:nodejs ./.next/static ./.next/static
 
 USER nextjs
 
@@ -59,5 +60,5 @@ ENV PORT=3000
 
 # server.js is created by next build from the standalone output
 # https://nextjs.org/docs/pages/api-reference/next-config-js/output
-ENV HOSTNAME="0.0.0.0"
+ENV HOSTNAME=${HOSTNAME}
 CMD ["node", "server.js"]
